= dfplayer Library for Arduino =

This library implements suport for the dfplayer mini serial
MP3 module.
http://www.picaxe.com/docs/spe033.pdf 

This library is operating-system independent; it requires only a C99-compliant
toolchain to compile, so it can be used for any microcontroller or fully-adorned
operating system application. The serial read/write operations used for
communication with the dfplayer device aren't implemented in this library,
but are accomplished via asynchronous callback functions which are implemented
for the desired operating system target. Example applications for various
operating systems can be found in the examples directory.

All operations implemented in this library are executed asynchronously;
response and event handling are performed exclusively via callback functions.
This is particularly well-suited for microcontroller application with no
multi-tasking support.

For more information about this library please visit:
https://github.com/zorxx/dfplayer

== License ==

Copyright 2017 Zorxx Software. All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
